BALLY_SPORTS_CHANNELS = ["bally sports southwest"]
LOCAL_CHANNELS = ["KDFW", "KXAS", "WFAA", "KTVT"]
NETWORK_CHANNELS = ["TNT", "TBS"]
TWENTY_FOUR_SEVEN_SHOWS = [
    "king of the hill",
    "always sunny in philadelphia",
    "i love lucy",
    r"^Friends$",
    "Seinfeld",
    r"The Office",
    "iCarly",
    "fresh prince of bel-air",
    "FUTURAMA",
    "SPONGEBOB SQUAREPANTS",
    "SIMPSONS",
]

EXCLUDE_GROUPS = [
    "MLS",
    "ADULT",
    "BRAZIL",
    "CANADA",
    "CARIBBEAN",
    "DAZN",
    "ECB Cricket",
    "ESPN Play (AU|JM|NL)",
    r"ESPN Plus \(B\)",
    "F1 TV",
    "FILIPINO",
    "FUBO",
    "FUTBOL/RUGBY",
    "INDIAN",
    "LATINO",
    "MiLB",
    "MLS",
    "NCAAF",
    "NCAAB",
    "NCAA BASEBALL",
    "MotoGP",
    "MUSIC",
    "NCAAW",
    "Optus",
    "Peacock",
    "PORTUGAL",
    "Sky Sport",
    "Religion",
    "Regional Locals",
    "Samsung TV",
    "Spectrum",
    "Supercross",
    "Supersport",
    "Tennis",
    "UK",
    "Vidio",
    "WNBA",
    "YouTube",
]

EXCLUDED_NETWORK_TV_CHANNELS = [
    r"\bWEST\b",
    r"\bEAST\b",
    "Low",
    "BLACK NEWS",
    "CHEDDAR",
    r"\bCW\b",
]

SPORTS_CHANNELS = [
    "ESPN2",
    "ESPN News",
    "ESPNU",
    "FOX Sports [12]",
    "(NFL|MLB|NHL) Network$",
    "NBA TV",
    "GOLF Channel",
    "AAC Network",
    "SEC Network",
    "^BIG TEN Network$",
    "CBS Sports Network",
    "MSG( 2)?",
    "MSGSN [12]$",
    "NBCSN$",
    "pac-12 network$",
    "TSN [1-5]",
    "sportsnet pittsburgh",
    "YES Network$",
]
